---
# This role sets up the necessary user environments for aws and vbox

- name: set up .bashrc
  become: true
  lineinfile:
    dest: "{{ item[0].path }}/.bashrc"
    line: "{{ item[1] }}"
    owner: "{{ item[0].owner }}"
    group: "{{ item[0].owner }}"
  with_nested:
    - "{{ paths }}"
    - "{{ bashrclines }}"

- name: create matplotlib config dirs
  become: true
  file:
    path: "{{ item[0].path }}/{{ item[1].path }}"
    state: "{{ item[1].state }}"
    owner: "{{ item[0].owner }}"
    group: "{{ item[0].owner }}"
  with_nested:
    - "{{ paths }}"
    - "{{ matplotlibrclines }}"

- name: set up matplotlibrc
  become: true
  lineinfile:
    dest: "{{ item.path }}/.config/matplotlib/matplotlibrc"
    line: "backend: agg"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
  with_items: "{{ paths }}"

- name: set up ssh (general)
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^PasswordAuthentication.*$', line: 'PasswordAuthentication yes' }
    - { regexp: '^.*Port.*$', line: 'Port 22' }

- name: restart ssh
  become: true
  service:
    name: ssh
    state: restarted

- name: create vboxsf group
  become: true
  group:
    name: vboxsf
    state: present

- name: create user account
  become: true
  user:
    name: "{{ ssh_username }}"
    password: "{{ ssh_password }}"
    shell: /bin/bash
    groups: sudo,vboxsf

- name: set up login screens
  become: true
  lineinfile:
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { dest: '/etc/update-motd.d/00-header', regexp: '^printf "Welcome to.*$', line: 'printf "Welcome to QIIME 2 Core 2.0.6!\n\n"' }
    - { dest: '/etc/update-motd.d/10-help-text', regexp: '^.*Documentation.*$', line: 'printf "  * Documentation: https://docs.qiime2.org/\n"' }
    - { dest: '/etc/update-motd.d/10-help-text', regexp: '^.*Support.*$', line: 'printf "  * Support: https://forum.qiime2.org/\n"' }
    - { dest: '/etc/update-motd.d/10-help-text', regexp: '^.*Management.*$', line: '' }

- name: add qiime logo to splash
  become: true
  blockinfile:
    dest: /etc/update-motd.d/00-header
    block: |
      cat<<"EOF"
      +-------------------------------------------------------------+
      |    ___      _____  _____  ____    ____  ________    _____   |
      |  .'   `.   |_   _||_   _||_   \  /   _||_   __  |  / ___ `. |
      | /  .-.  \    | |    | |    |   \/   |    | |_ \_| |_/___) | |
      | | |   | |    | |    | |    | |\  /| |    |  _| _   .'____.' |
      | \  `-'  \_  _| |_  _| |_  _| |_\/_| |_  _| |__/ | / /_____  |
      |  `.___.\__||_____||_____||_____||_____||________| |_______| |
      |                                                             |
      +-------------------------------------------------------------+
      EOF

- name: set hostname
  become: true
  hostname:
    name: "{{ hostname }}"
