---
# This role is for configuring the jump host

- name: set up prereqs
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - letsencrypt
    - nginx
    - nfs-common
    - nfs-kernel-server
    - htop

- name: set up nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default

- name: restart services
  service:
    name: nginx
    state: restarted

# - name: set up letsencrypt
#   command: "letsencrypt certonly --agree-tos --email {{ email }} -n -a webroot --webroot-path=/var/www/html -d {{ domain }}"
#   args:
#     creates: /etc/letsencrypt

- name: make sure certs dir is present
  file:
    path: /etc/letsencrypt
    state: directory

- name: copy certs
  unarchive:
    src: "{{ playbook_dir }}/../tmp/certs.tar.gz"
    dest: /
    owner: www-data
    group: www-data

- name: update nginx
  replace:
    dest: /etc/nginx/sites-available/default
    regexp: "#"
    replace: ""

- name: update nginx (part 2)
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: "listen 80 default_server;"
    line: ""

- name: create mount point
  file:
    path: /mnt/home
    state: directory
    mode: 0777
    owner: ubuntu
    group: ubuntu

- name: prep shared drive filesystem
  filesystem:
    fstype: ext4
    dev: /dev/xvdb

- name: mount ebs
  mount:
    name: /mnt/home
    src: /dev/xvdb
    fstype: auto
    state: mounted

- name: set up nfs server
  lineinfile:
    dest: /etc/exports
    insertafter: EOF
    line: "/mnt/home {{ vpc_cidr_block }}(rw,nohide,fsid=0,insecure,no_subtree_check,async)"

- name: set up /etc/skel/.bashrc
  lineinfile:
    dest: /etc/skel/.bashrc
    line: "{{ item }}"
  with_items:
    - export PATH="/mnt/home/miniconda3/bin:$PATH"
    - source tab-qiime

- name: create matplotlib config dirs and ssh dir
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items:
    - { path: '/etc/skel/.config', state: 'directory'}
    - { path: '/etc/skel/.config/matplotlib', state: 'directory'}
    - { path: '/etc/skel/.config/matplotlib/matplotlibrc', state: 'touch' }
    - { path: '/etc/skel/workshop', state: 'directory' }

- name: set up /etc/skel/.config/matplotlib/matplotlibrc
  lineinfile:
    dest: /etc/skel/.config/matplotlib/matplotlibrc
    line: "{{ item }}"
  with_items:
    - "backend: agg"

- name: create user accounts
  user:
    name: "{{ item.name }}"
    password: "{{ item.hash }}"
    group: "{{ item.group }}"
    uid: "{{ item.uid }}"
    shell: /bin/bash
    createhome: True
    home: "/mnt/home/{{ item.name }}"
  with_items: "{{ users }}"

- name: create admin accounts
  user:
    name: "{{ item }}"
    password: "$6$rounds=656000$ycPDEjJbFznV6P00$Vp1EqUejMU/GVaLgO04Qv6XuZ5M3p3tPakCrPB7kSoxMBn3euWFok4tCA9b1dCYDpanjU5.0SWOn/rRtUwZ900"
    shell: /bin/bash
    createhome: True
    home: "/home/{{ item }}"
  with_items:
    - admin1
    - admin2
    - admin3

- name: configure ssh for jumping
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item }}"
    block: |
      Match Group {{ hostvars[item]['grp'] }}
          ForceCommand ssh {{ item }}
  with_items: "{{ groups['compute_hosts'] }}"

- name: restart services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - ssh
    - nfs-kernel-server
    - nginx

- name: remove known_hosts
  file:
    path: "/mnt/home/{{ item.name }}/.ssh/known_hosts"
    state: absent
  with_items: "{{ users }}"

- name: shared data dir
  file:
    path: "/mnt/home/{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - shared
    - shared/qiime2-moving-pictures-tutorial
    - shared/qiime2-moving-pictures-tutorial/raw-sequences

- name: download data
  get_url:
    url: "{{ item.url }}"
    dest: "/mnt/home/shared/qiime2-moving-pictures-tutorial/{{ item.dest }}"
    mode: 0777
    force: False
    timeout: 60
  with_items:
    - { url: "https://docs.google.com/spreadsheets/d/1_3ZbqCtAYx-9BJYHoWlICkVJ4W_QGMfJRPLedt_0hws/export?gid=0&format=tsv", dest: "sample-metadata.tsv" }
    - { url: "https://data.qiime2.org/2.0.6/tutorials/moving-pictures/raw-sequences/barcodes.fastq.gz", dest: "raw-sequences/barcodes.fastq.gz" }
    - { url: "https://data.qiime2.org/2.0.6/tutorials/moving-pictures/raw-sequences/sequences.fastq.gz", dest: "raw-sequences/sequences.fastq.gz" }
