---
# This role cleans up the user environment for vbox

- name: hide ubuntu user from login screen
  become: true
  blockinfile:
    dest: /var/lib/AccountsService/users/ubuntu
    create: yes
    block: |
      [User]
      SystemAccount=true

- name: init qiime2 cache
  become: true
  become_user: qiime2
  become_method: sudo
  environment:
    PATH: "/miniconda3/bin"
  command: "qiime dev refresh-cache"

- name: remove sudo banner warning
  become: true
  become_user: qiime2
  become_method: sudo
  file:
    path: ~/.sudo_as_admin_successful
    state: touch
    owner: qiime2
    group: qiime2

- name: install leafpad editor
  become: true
  apt:
    name: leafpad

- name: set leafpad as default editor
  become: true
  lineinfile:
    dest: /usr/share/applications/defaults.list
    regexp: "text/plain"
    line: "text/plain=leafpad.desktop"

- name: set up unity launcher
  become: true
  become_user: qiime2
  become_method: sudo
  command: |
    dbus-launch gsettings set com.canonical.Unity.Launcher favorites "['application://gnome-terminal.desktop','application://firefox.desktop','application://leafpad.desktop','application://org.gnome.Nautilus.desktop','unity://running-apps','unity://expo-icon','unity://devices']"

- name: create local apps dir
  become: true
  become_user: qiime2
  become_method: sudo
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
  with_items:
    - { path: '/home/qiime2/.local', state: 'directory' }
    - { path: '/home/qiime2/.local/share', state: 'directory' }
    - { path: '/home/qiime2/.local/share/applications', state: 'directory' }

- name: qiime2 user amazon unity overrides
  become: true
  become_user: qiime2
  become_method: sudo
  copy:
    remote_src: true
    src: /usr/share/applications/ubuntu-amazon-default.desktop
    dest: ~/.local/share/applications/ubuntu-amazon-default.desktop

- name: hide amazon for user qiime2
  become: true
  become_user: qiime2
  become_method: sudo
  lineinfile:
    dest: '/home/qiime2/.local/share/applications/ubuntu-amazon-default.desktop'
    line: 'Hidden=true'
