---

- hosts: localhost
  connection: local
  vars_files:
    - ../group_vars/all
  roles:
    - ../roles/aws-allocate

- hosts: all_hosts
  remote_user: ubuntu
  gather_facts: False
  roles:
    - ../roles/bootstrap

- hosts: all_hosts
  remote_user: ubuntu
  become: True
  vars_files:
    - ../group_vars/all
  roles:
    - ../roles/common

- hosts: jump_hosts
  remote_user: ubuntu
  become: True
  vars_files:
    - ../group_vars/all
  vars:
    users: "{{ lookup('file', '../tmp/roster.json') | from_json }}"
  roles:
    - ../roles/jump
    - ../roles/qiime2

- hosts: compute_hosts
  remote_user: ubuntu
  become: True
  vars_files:
    - ../group_vars/all
  vars:
    users: "{{ lookup('file', '../tmp/roster.json') | from_json }}"
  roles:
    - ../roles/compute
